#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
    BOLD=$(tput bold)
                     DIM=$(tput dim)
                                      RESET=$(tput sgr0)
    BLUE=$(tput setaf 4)
                        GREEN=$(tput setaf 2)
                                               YELLOW=$(tput setaf 3)
                                                                       # shellcheck disable=SC2034 # available for authored stages
                                                                       RED=$(tput setaf 1)
else
    BOLD=""
           DIM=""
                   RESET=""
                             BLUE=""
                                      GREEN=""
                                                YELLOW=""
                                                           # shellcheck disable=SC2034 # available for authored stages
                                                           RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
    [[ -t 1 ]] || return 0
    if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
    _clear
    printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
    printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
    printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
    printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
    printf '  later, since it remembers values already saved.%s\n' "$RESET"
    pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
    _clear
    _STAGE_INDEX=$((_STAGE_INDEX + 1))
    printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
        "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
    local url="$1"
    printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
    {
        if command -v wslview   >/dev/null 2>&1; then
                                                      wslview "$url"
        elif command -v explorer.exe >/dev/null 2>&1; then
                                                       explorer.exe "$url"
        elif command -v xdg-open >/dev/null 2>&1; then
                                                      xdg-open "$url"
        elif command -v open    >/dev/null 2>&1; then
                                                      open "$url"
        else warn "couldn't open a browser; visit it manually: $url"; fi
    } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
    printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
    read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
    local reply=""
    printf '  %s? %s [y/N] ' "$YELLOW" "$1"
    read -r reply || true
    [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
    [[ -f "$ENV_FILE" ]] || return 1
    local line
              line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
    printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
    local key="$1" prompt="$2" current input
    current=$(_existing "$key" || true)
    if [[ -n "$current" ]]; then
        printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
    else
        printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
    fi
    read -r input || true
    [[ -z "$input" && -n "$current" ]] && input="$current"
    printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
    local key="$1" prompt="$2" current input
    current=$(_existing "$key" || true)
    if [[ -n "$current" ]]; then
        printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
    else
        printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
    fi
    read -rs input || true
    printf '\n'
    [[ -z "$input" && -n "$current" ]] && input="$current"
    printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
    local key="$1" value="$2" tmp
    touch "$ENV_FILE"
    tmp=$(mktemp)
    grep -vE "^${key}=" "$ENV_FILE" >"$tmp" || true
    printf '%s=%s\n' "$key" "$value" >>"$tmp"
    mv "$tmp" "$ENV_FILE"
    WRITTEN_ENV+=("$key")
    printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
    local name="$1" value="$2"
    if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
        if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
            WRITTEN_SECRET+=("$name")
            printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
            return
        fi
    fi
    SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
    warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
    local name="$1" value="$2"
    if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
        if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
            printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
            return
        fi
    fi
    SKIPPED+=("GitHub variable $name")
    warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
    _clear
    printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
    ((${#WRITTEN_ENV[@]}))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
    ((${#WRITTEN_SECRET[@]})) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
    if ((${#SKIPPED[@]})); then
        printf '\n'
                 warn "still to do by hand:"
        for s in "${SKIPPED[@]}"; do note "  - $s"; done
    fi
    printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

banner "release-please GitHub App setup"
say "release-please needs to push a tag from a workflow, and GitHub's own loop"
say "prevention silently swallows that push when it's authored by the default"
say "GITHUB_TOKEN. The fix is a small, narrowly-scoped GitHub App whose token"
say "release-please's workflow mints for itself. This wizard creates that App,"
say "installs it on mgoodness/skl, and stores its Client ID and private key"
say "where the release-please.yml workflow expects them."

# ── Stage 1: create the App ────────────────────────────────────────────────
stage "Create the GitHub App"
say "GitHub App registration doesn't accept permissions via URL parameters,"
say "so set them by hand on the form."
open_url "https://github.com/settings/apps/new"
step "GitHub App name: something unique, e.g. \"skl-release-please\"."
step "Homepage URL: https://github.com/mgoodness/skl (anything valid works)."
step "Webhook: uncheck \"Active\" — this App only mints tokens, it never receives events."
step "Repository permissions → Contents: Read and write."
step "Repository permissions → Pull requests: Read and write."
step "\"Where can this GitHub App be installed?\": Only on this account."
step "Click \"Create GitHub App\" at the bottom."
pause "Created it? Press Enter to continue."

# ── Stage 2: capture the Client ID ──────────────────────────────────────────
stage "Capture the Client ID"
say "You should now be on the new App's settings page (General tab)."
step "Under \"About\", copy the \"Client ID\" value (starts with Iv1. or Iv23.)."
ask RELEASE_PLEASE_APP_CLIENT_ID "Paste the Client ID:"
write_env RELEASE_PLEASE_APP_CLIENT_ID "$RELEASE_PLEASE_APP_CLIENT_ID"
set_var RELEASE_PLEASE_APP_CLIENT_ID "$RELEASE_PLEASE_APP_CLIENT_ID"

# ── Stage 3: generate and capture the private key ───────────────────────────
stage "Generate a private key"
say "Still on the App's settings page, scroll to \"Private keys\"."
step "Click \"Generate a private key\" — a .pem file downloads automatically."
ask "RELEASE_PLEASE_APP_KEY_PATH" "Paste the path to the downloaded .pem file:"
if [[ -f "$RELEASE_PLEASE_APP_KEY_PATH" ]]; then
    RELEASE_PLEASE_APP_PRIVATE_KEY=$(cat "$RELEASE_PLEASE_APP_KEY_PATH")
    set_secret RELEASE_PLEASE_APP_PRIVATE_KEY "$RELEASE_PLEASE_APP_PRIVATE_KEY"
    note "the private key itself is never written to $ENV_FILE — only the App's Client ID is."
else
    warn "couldn't find $RELEASE_PLEASE_APP_KEY_PATH"
    SKIPPED+=("GitHub secret RELEASE_PLEASE_APP_PRIVATE_KEY (set it manually: gh secret set RELEASE_PLEASE_APP_PRIVATE_KEY < path/to/key.pem)")
fi

# ── Stage 4: install the App on this repo ───────────────────────────────────
stage "Install the App on mgoodness/skl"
say "The App exists but isn't installed anywhere yet — installing it is what"
say "actually grants it access to this repo."
step "On the App's settings page, click \"Install App\" in the left sidebar."
step "Choose your account, then \"Only select repositories\" → mgoodness/skl."
step "Click \"Install\"."
if confirm "Installed it on mgoodness/skl?"; then
    note "good — release-please.yml can now mint a token scoped to this repo."
else
    SKIPPED+=("Installing the App on mgoodness/skl (Settings → Install App)")
fi

finish
